### ISSUE TITLE
Suggestion: disable save on change

### ISSUE THREAD

**Issue by akatsukle** [hrai/auto-save-vs-extension#12]
Thank you for the extension, this is working great !
I am using this for the auto save when my visual studio loses focus, but I do not like the auto-save on delay. I am working with Xamarin forms, and they have a "Live Reload" feature: when you save a xaml file your application is automatically updated on the phone, while running without needing to recompile.

If the auto-save kicks in when a xaml file is in an invalid state, this causes live reload to crash ;(.

It would be great to be able to disable the auto-save on a timer feature. 
As a workaround, I simply set a big delay.

**Comment by hrai** [comment]
Doesn't excluding xaml files in the extension settings help with your case?

https://github.com/hrai/auto-save-vs-extension/blob/master/options.png

**Comment by akatsukle** [comment]
Well I still want to save xaml files when the focus changes.

**Comment by hrai** [comment]
In that case, https://marketplace.visualstudio.com/items?itemName=mcright.auto-save might be the right extension for you.
