### ISSUE TITLE
"Only exception is when the last added character was period[.]" stopped working

### ISSUE THREAD

**Issue by dlplenin** [hrai/auto-save-vs-extension#15]
My environment:

- VS2019 16.7.0.
- SO:  Win10 Pro

This (necessary / perfect) extension was working perfectly. But now when the last character is a period and Im looking in the suggestion provided by IntelliCode this list closes after the delay time is reached.

Tks for this extension, time and effort!

**Comment by hrai** [comment]
Duplicates https://github.com/hrai/auto-save-vs-extension/issues/14
