### ISSUE TITLE
File is always saved on focus change, even if not edited

### ISSUE THREAD

**Issue by mbechard** [hrai/auto-save-vs-extension#16]
Thanks for this great extension! One issue I'm seeing is that it's always saving a file when it loses focus, even if it hasn't been modified. I can see this just by clicking between tabs of open files. This causes lots of unnecessary compiling of these files. Is this expected?
VS2019

**Comment by hrai** [comment]
@mbechard what sort of files are these? Are you using auto-formatter by any chance that's formatting the files as they're opened?

This extension doesn't differentiate a user modified files from auto-modified ones and applies `Save` on all the files by default.

**Comment by mbechard** [comment]
.C and .h files. I am using the clang-format that is natively integrated with VS. However that's not showing up as modifying the files when I click on them. I'll try turning them to manual-only triggered formatting and see if that is the root issue here.
