### ISSUE TITLE
autosave on Preview rename ,This will cause vs2019 to not respond.

### ISSUE THREAD

**Issue by magian1127** [hrai/auto-save-vs-extension#19]
![111](https://user-images.githubusercontent.com/14800320/113299768-cc951380-932f-11eb-87e6-b8a09af02e14.gif)

When previewing, the file is saved automatically, and then the preview window cannot be closed.
预览时,自动保存了文件,然后预览窗口就无法关闭了

**Comment by hrai** [comment]
@magian1127 unfortunately I couldn't replicate this issue.
