### ISSUE TITLE
Suggestions: Exclude list

### ISSUE THREAD

**Issue by Barina** [hrai/auto-save-vs-extension#2]
Would be nice to have an exclude list.

**Comment by hrai** [comment]
I don't follow. What sort of list do you mean? Did you mean file types?

**Comment by Barina** [comment]
Yes for file types/extensions 
And now I think maybe for projects/solutions as well..
Lets say I'm developing a Unity game and I don't want to save every second (so Unity won't compile on every save) and in the same time I work on a WPF application where I do want to save on every change but not when I'm querying from a database

**Comment by hrai** [comment]
@Barina I've created a new pr to add this feature in. Can you review it pls?
