### ISSUE TITLE
VS2019 hangs during build

### ISSUE THREAD

**Issue by SamMackrill** [hrai/auto-save-vs-extension#20]
With this extension enabled then my build hangs as unresponsive for an hour, although it eventually succeeds
When disabled build takes around 15 seconds and no hang

**Comment by SamMackrill** [comment]
Have to disable this extension, sad times :(

**Comment by SamMackrill** [comment]
Happy to help diagnose this

**Comment by hrai** [comment]
@SamMackrill  Can you add some more info? Eg what sort of project it is etc.

This extension does not trigger anything unless a file content changes in the VS editor so I'm thinking if this is due to something else and is more of a red herring.

**Comment by SamMackrill** [comment]
All I have to do to fix my build issue is disable this extension, although I guess something else may be triggering a file change during compilation and so confusing everything.

**Comment by SamMackrill** [comment]
> @SamMackrill Can you add some more info? Eg what sort of project it is etc.
> 
> This extension does not trigger anything unless a file content changes in the VS editor so I'm thinking if this is due to something else and is more of a red herring.

Sorry I missed this, will try and get more details

**Comment by SamMackrill** [comment]
This is a solution with 14 C# projects, clean build with auto-save disabled takes a few seconds
When enabled VS hangs (application unresponsive) about half way through
does eventually finish
![image](https://user-images.githubusercontent.com/84898/134159325-a6ce2617-78f2-40c5-8482-f0cb1ed5d703.png)
Other Extensions:

- JetBrains Resharper
- Visual Studio Rich Navigation
- Visual Studio Intellicode
- Cloud Explorer for VS2019 Preview
- Visual Studio Extensions for Windows Library for JavaScript
- MS Advertising SDKs

**Comment by benjaminvanrenterghem** [comment]
> This is a solution with 14 C# projects, clean build with auto-save disabled takes a few seconds When enabled VS hangs (application unresponsive) about half way through does eventually finish ![image](https://user-images.githubusercontent.com/84898/134159325-a6ce2617-78f2-40c5-8482-f0cb1ed5d703.png) Other Extensions:
> 
> * JetBrains Resharper
> * Visual Studio Rich Navigation
> * Visual Studio Intellicode
> * Cloud Explorer for VS2019 Preview
> * Visual Studio Extensions for Windows Library for JavaScript
> * MS Advertising SDKs

What's the verdict after disabling the other extensions and solely using this one?
