### ISSUE TITLE
Vs2022 support

### ISSUE THREAD

**Issue by ArgTang** [hrai/auto-save-vs-extension#21]
Any plans to support vs2022?

**Comment by hrai** [comment]
As per Microsoft's comments below, I won't release a new 2022 version in the marketplace until they support multiple vsix versions.

```
For the preview releases of Visual Studio 2022, the Marketplace will only support a single VSIX file per Marketplace listing. While Visual Studio 2022 is in preview we encourage you to have a separate Visual Studio 2022 only Marketplace listing for your extension.
```

But I have been playing around with the Visual Studio 2022 preview version and so far the latest changes seem to work.

Here's the extension file if you'd like to download and install it locally.

When the updated extension is ready, I'll publish it in the marketplace.

[AutoSaveFile64.zip](https://github.com/hrai/auto-save-vs-extension/files/6921103/AutoSaveFile64.zip)
