### ISSUE TITLE
The extension will automatically save the standard header file.

### ISSUE THREAD

**Issue by zhengweidi** [hrai/auto-save-vs-extension#22]
Saving the standard header file will cause a pop-up window.
![image](https://user-images.githubusercontent.com/31889177/130719688-5a2f353b-f97d-46cc-9b60-5615107b781a.png)

**Comment by hrai** [comment]
I don't use header files so not sure if I can be of much help. I'll open it up for the community.

**Comment by zhengweidi** [comment]
I am not very familiar with dotNET, but I see that there is a Project property in this [document](https://docs.microsoft.com/en-us/dotnet/api/envdte.window.project?view=visualstudiosdk-2019) , which may be used to determine whether the current document belongs to the Project.
This problem should be solved by not saving files that are not part of the project.
