### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by stevebroshar** [hrai/auto-save-vs-extension#28]
I don't see this extension available for VS2022. It is available for VS2019. What needs to happen for this to be available for VS2022?

I do [read](https://developercommunity.visualstudio.com/t/visual-studio-2022-auto-save-file-feature-suggesti/1453919) that a prerelease version of VS2022 did have an auto save feature. But, I don't see an option to enable in 17.0.0 (community). Even the linked info hints that it was removed in a subsequent version. If that feature were available, then wouldn't need this extension. But, until or unless that feature is available, this extension is useful.

**Comment by robinlarondelle** [comment]
I'd like to contribute to this project if you don't feel like you have the time to update this extension. I see in the commit history that the extension is updated to support VS 2022, however i can't see the extension in the Visual Studio Extension store. What is left to be done to have it placed in the store?

**Comment by hrai** [comment]
@stevebroshar @robinlarondelle I am not able to publish to the extension store because of incompatibility issue just yet but here's a copy of the local build for VS2022 that works just fine. I will upload this when it is supported on the store.

https://github.com/hrai/auto-save-vs-extension/issues/21#issuecomment-891521506

**Comment by robinlarondelle** [comment]
Ahh i get it. Alright, then we'll wait for them to enable support ;) Thanks

**Comment by hrai** [comment]
Xmas came early. I've uploaded the x64 version to the store and published it. @robinlarondelle @stevebroshar

**Comment by stevebroshar** [comment]
Super thanks
