### ISSUE TITLE
Auto save works when a file auto opened by debugger breakpoint, causing endless spam of "save" windows.

### ISSUE THREAD

**Issue by emelrad12** [hrai/auto-save-vs-extension#29]
Steps to reproduce:
Make some invalid code, that writes to position 10 on vector with 10 length.
Debug it, the debugger steps in some vector file.
The file is for some reason modified, autosave spams "save" dialog, cause it can't overwrite it.

Suggestion: Don't autosave files that cant be overwritten.

**Comment by hrai** [comment]
Can you post a sample code? I'll try and replicate it.

@emelrad12
