### ISSUE TITLE
Suggestions: Save-on-Change

### ISSUE THREAD

**Issue by Barina** [hrai/auto-save-vs-extension#3]
Please add an option to auto save when file changed.

**Comment by hrai** [comment]
This is the default behaviour of the extension. If anything changes on the file, then it gets saved.

**Comment by Barina** [comment]
Oh that was quick lol
I figured out you need to set the delay to zero to get this option working
And in this configuration it won't try to save new files so no annoying "Save As" dialogues when you don't want them
Thanks

**Comment by hrai** [comment]
That's great. Perhaps the description on the plugin wasn't descriptive enough. Let me see if I can update it. Otherwise I'll close this issue.
