### ISSUE TITLE
autosave without formatting

### ISSUE THREAD

**Issue by BachiMjavanadze** [hrai/auto-save-vs-extension#32]
I have configured my VS formatting on save, but I do not need your "Auto Save Extension" to format document every time when it saving document. I need to format document only when I press "ctrl+s". Please fix it.

**Comment by hrai** [comment]
It's not the extension that's formatting your doc.

This 'formatting on save' is hooked up to the 'save' feature so if you trigger a manual save or automatic save, the result will be the same. 

If you don't want to auto-save, simply uninstall the extension :smiley:
