### ISSUE TITLE
File Type Includes in addition to Excludes? 

### ISSUE THREAD

**Issue by atljoseph** [hrai/auto-save-vs-extension#33]
The referenced line of code is whitespace, but the location of it is relevant:
https://github.com/hrai/auto-save-vs-extension/blob/d20401fd8681c83b9883efc0f27e58776ffad561/AutoSaveFileShared/Helper.cs#L58

1. What if ignoredFileTypes could take in “*” for excluding all file types?
2. What if there was an includeFileTypes checked above the ignoredFileTypes, which operated by the same rules? 

Wanting to save a handful of file types automatically, without having to know all the file types in advance. 

Am surprised VSCode doesn’t have this feature already. Thanks for making it a reality!

**Comment by hrai** [comment]
@atljoseph 

1. What you're asking for is disabling the extension which you can do in the IDE.
2. includeFileTypes will conflict with ignoredFileTypes. I'll have to see if this gets anymore upvotes before I can integrate this change.

**Comment by atljoseph** [comment]
Yeah they conflict. That is the point. I’ll just write my own in typescript, thanks. This isn’t that complicated.
