### ISSUE TITLE
VS2022 kills IntelliSense popup

### ISSUE THREAD

**Issue by deakjahn** [hrai/auto-save-vs-extension#34]
Unfortunately, using the extension collides with the IntelliSense popup in VS2022. The error was reported as https://developercommunity.visualstudio.com/t/intellisense-popup-timeout/1670568 but it turned out to be Auto Save-related.

The Intellisense popup appears when there is a suggestion to make and it disappears after a set timeout. The problem is that the timeout elapses even if I’m using the arrow keys to step between the suggested items, not just only when the IDE is left idle. This means that there’s hardly any time to read, evaluate and select an item not immediately at the top of the list.

Popups asked for specifically (eg. Ctrl+Space) work all right. The trouble applies to the automatically appearing popup when using Options > Text Editor > language > IntelliSense > Show completion list after a character is typed.

**Comment by deakjahn** [comment]
Screen capture:

![Animation](https://user-images.githubusercontent.com/2234271/156373675-93e9a1f9-c355-4e43-805e-4473f09c7acc.gif)

(I start to type, the popup opens, I start to go down with the Down arrow key and the popup disappears.)

**Comment by hrai** [comment]
@deakjahn

This is because of the VS's behaviour that the popups close on `Save`.

One option that's worked for me is to up the `Time Delay` to a higher value that the default of 5 seconds.

**Comment by deakjahn** [comment]
@hrai I mentioned your opinion in the issue queue there, could you by any chance chime in there? A solution might eventually emerge, if we're lucky. :-)
