### ISSUE TITLE
Save only when file has been modified?

### ISSUE THREAD

**Issue by alteredtastes** [hrai/auto-save-vs-extension#35]
I rely on this functionality as I develop and am really surprised it's not even built-in for VS. Your extension has helped for sure, but it can also really slow down my system with my setup because I need to develop while I have a build process running in watch mode. The extension seems to save a new file regardless of whether a change was made, so when I navigate across my files without changing anything, my build's watch process notices every single new file that was saved, though none actually had any new changes at all.

Would it be straightforward to enhance the extension so it only saves files if changes had actually been made to them?

**Comment by hrai** [comment]
@alteredtastes you should now be able to use the option `Save File When It Loses Focus` that I've added here https://github.com/hrai/auto-save-vs-extension/blob/master/options.png
