### ISSUE TITLE
The extension repeatedly displays file save dialog

### ISSUE THREAD

**Issue by BachiMjavanadze** [hrai/auto-save-vs-extension#38]
When I add a table in `Visual Studio IDE's` `SQL Server Object Explorer` then a file save dialog pops up repeatedly to save the SQL query:

![NZKdn](https://i.stack.imgur.com/NZKdn.gif)

To fix the problem I just exclude sql files saving:

![exlude](https://user-images.githubusercontent.com/38082501/221222251-dfa22fc2-595c-474c-a6e8-d68bde805476.png)

but now  save dialog pops up when the `Visual Studio IDE` loses focus.

Please fix it. 

If it is not a bug but it is a feature, please add extra option in the extension settings, something like this:

`exclude file when IDE loses focus: sql`

**Comment by hrai** [comment]
It's already configurable. 

You can set the value of `save all files when vs loses focus` to `False`

**Comment by BachiMjavanadze** [comment]
> It's already configurable.
> 
> You can set the value of `save all files when vs loses focus` to `False`

but you can't `save current script when tab loses focus`...
and this is not my request

**Comment by hrai** [comment]
I see.

You can disable auto-save when the IDE loses focus.

You can always hop back in to manually save the SQL files as needed. As for other files, they automatically get saved when the window loses focus.

There's 2 scenarios/events.
- The window loses focus. this is your primary IDE and is only 1.
- There may be multiple files open in an IDE. Such as 1 for each file that's open.
