### ISSUE TITLE
Extension interferes with Intellisense display

### ISSUE THREAD

**Issue by RockyRoads2591** [hrai/auto-save-vs-extension#39]
When the extension is active, anytime the file save happens, intellisense suggestions that are displaying disappear and you can't get them back unless you start over.  Disabling this extension, cured the problem.

**Comment by volodymyr-matselyukh** [comment]
Agree with Rocky. The same is happening when you use Ctrl+R+R to rename your class name or variable name across the app. After extension saves the file the renaming completes on a half road and you need to rename once again and if it's a long file/variable name then it's very annoying. 

Also, it's not obvious that this extension is leading to losing a focus problem, especially, when you install plugin and forget about coding for a month and then start discovering strange issues with losing the focus. First I thought I have some virus on my PC.

It's worth mention at least this issue somewhere at the top of extension description.

**Comment by hrai** [comment]
This is the default behaviour when you hit `Save`.

You can change `time delay` setting in options https://github.com/hrai/auto-save-vs-extension#configurable-settings
