### ISSUE TITLE
Project Properties Page does not Auto-Save

### ISSUE THREAD

**Issue by friedrich-brunzema** [hrai/auto-save-vs-extension#4]
Hi,

if you go to a .csproj in Solution Explorer, right click -> Properties and then go to the Debug settings, and make a change to say the application arguments, it is not saved automatically.  

It would be really cool if it were possible.  Depending on how much this bugs me, I may look at it and submit a PR, but no promises.  If you do a File->Save All, the project properties page does get changed, so maybe that is the one you want to use...

F.

**Comment by hrai** [comment]
This is because the logic to save only kicks in for 'document' files.

Let me see if I can add csproj file to an exception's list.

**Comment by hrai** [comment]
Looks like I will need to listen to a different type of event. This will need more investigation.

**Comment by hrai** [comment]
The below should fix the issue.

https://github.com/hrai/auto-save-vs-extension/pull/5

**Comment by friedrich-brunzema** [comment]
Wow, this is great -- will check this out!  This was a real nuisance to me -- I would change command line parameters - rebuild and run, and the old, saved arguments would be used.  I then had to save the project specifically and re-run.

Thanks so much, will give it a try.

**Comment by friedrich-brunzema** [comment]
Hmm, just tested it (checked out the code, master branch), re-installed the extension, and it does not seem to work :-(
What I did:
1. Open a solution
2. Get to a .csproj (Project Properties)
3. Change parameters in the Debug options (e.g. arguments) - this results in a *
4. Wait 5+ seconds
5. The file is not saved (*) remains.

Then tried making a change to a regular file as well -- after 5 sec, the changed file is saved, but the project property file is not saved.

**Comment by hrai** [comment]
I've replicated the issue. The change event is intermittently intercepted by the plugin. So at this stage, it looks like this will be an extensive solution with further investigation. 

I'll add this as a new feature when I get more time.

**Comment by hrai** [comment]
@friedrich-brunzema I've released a new feature where if VS loses focus, all the files are saved including the designer as discussed in #7 .

May be you could look at this as a temp solution.

**Comment by friedrich-brunzema** [comment]
Hi,
I'm afraid that workgaround won't help for the use case I am looking at.  The use case is this:  I am debugging a command line app with different commands.  
#1 Set up the debugger (in project properties) for use case #1, save the property
#2 Work on functionality for use case #2.  Change command line args in the property sheet for project. (Don't explicitly save)
#3 Recompile (note that the property sheet does NOT get saved!
#4 F5 to debug.  The debugger starts with the settings with as set in #1 

To remedy is simple, but annoying -- open the Tab, hit save (Ctrl+S) and F5.
Just wondering Visual Studio Team has this behavior -- is this by design? And if so why?  If not, should this be fixed in VS, rather than in an extension?  The fact that it is not trivial to do in an extension also says something.

**Comment by hrai** [comment]
Unfortunately, I haven't been able to find a way to intercept the changes event to the properties window. I'll keep an eye on it.
