### ISSUE TITLE
autosave when Visual Studio loses focus

### ISSUE THREAD

**Issue by mrjohnr** [hrai/auto-save-vs-extension#7]
Hi
it is possible to save also when Visual Studio loses focus?
currently i'm using [this solution for that](https://stackoverflow.com/a/33592923/3492996)
thanks

**Comment by mrjohnr** [comment]
Hi. I've found a little issue:I'm working with Vs+Angular.when I switch between Vs tabs (there is no change made to any file ) seems the project is automatically saved and Angular rebuilds and re-sync  browser.can that be fixes?.I've disabled the extension,switched back to my old solution described in post#1 and all works fine.thanks

**Comment by hrai** [comment]
This is not something that the extension can control. The files get saved
when visual studio loses focus and that's all it does. Unfortunately
there's no answer to your problem. You can disable this feature rather than
the whole extension in the options dialogue box though.

**Comment by mrjohnr** [comment]
k.thanks
