### ISSUE TITLE
What does the Mode option do?

### ISSUE THREAD

**Issue by michaelkonecny** [hrai/auto-save-vs-extension#9]
What does the Mode option do?

I'm just curious. It would be nice to document it (I'm happy to do it).

**Comment by hrai-domain** [comment]
I don't follow. Could you add a screenshot please?

**Comment by hrai-domain** [comment]
Looks like the screenshot is outdated, I'll raise a PR to fix it.

**Comment by hrai** [comment]
Looks like the screenshot is outdated, I'll raise a PR to fix it.
